services:
  mockoon-services:
    build:
      context: ./mockoon-container
    networks:
      - api_gateway_network
    ports:
      - "3003:3003"
      - "3004:3004"
      - "3005:3005"
    restart: always  # 👈 add this line

  nginx:
    build:
      context: .
    networks:
      - api_gateway_network
    ports:
      - "80:80"
    restart: always  # 👈 add this line