name: Simple CI/CD for NGINX API Gateway
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Debug Docker Login
        run: |
          echo "Username: ${{ secrets.DOCKERHUB_USERNAME }}"
          echo "Token starts with: dckr_pat_"
          docker --version
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push NGINX
        run: |
          docker build -t lyhor/nginx-api-gateway:latest .
          docker push lyhor/nginx-api-gateway:latest
      
      - name: Build and push Mockoon
        run: |
          docker build -t lyhor/mockoon-services:latest ./mockoon-container
          docker push lyhor/mockoon-services:latest
